# Generated by Django 6.0.4 on 2026-04-29 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallazgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Acción')),
                ('fecha_compromiso', models.DateField(verbose_name='Fecha Compromiso')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='hallazgos.hallazgo', verbose_name='Hallazgo Relacionado')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Acción Correctiva',
                'verbose_name_plural': 'Acciones Correctivas',
                'ordering': ['fecha_compromiso'],
            },
        ),
    ]
