# Generated by Django 6.0.4 on 2026-04-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Bitácora',
                'verbose_name_plural': 'Eventos de Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
