# Generated by Django 6.0.4 on 2026-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('auditor_lider', 'Auditor Líder'), ('auditor', 'Auditor'), ('auditado', 'Auditado')], default='auditado', max_length=20, verbose_name='Rol'),
        ),
    ]
