# Generated by Django 6.0.4 on 2026-04-29 19:45

import django.db.models.deletion
import evidencias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acciones_correctivas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=evidencias.models.evidencia_upload_path, verbose_name='Archivo de Evidencia')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción / Comentario')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='acciones_correctivas.accioncorrectiva', verbose_name='Acción Correctiva')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
    ]
