# Generated by Django 6.0.4 on 2026-04-29 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('Planeada', 'Planeada'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Finalizada', 'Finalizada')], default='Planeada', max_length=20, verbose_name='Estado')),
                ('criticidad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('N/A', 'N/A')], default='N/A', max_length=10, verbose_name='Criticidad')),
                ('alcance', models.TextField(blank=True, verbose_name='Alcance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_lideradas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Líder')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
