# Generated by Django 6.0.4 on 2026-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='area',
            field=models.CharField(default='General', max_length=100, verbose_name='Área / Departamento'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='norma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Norma de Referencia'),
        ),
    ]
