# Generated by Django 6.0.4 on 2026-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_auditoria_area_auditoria_folio_auditoria_norma'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción / Objetivo'),
        ),
    ]
