# Generated by Django 5.2.8 on 2026-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0003_auditoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='folio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Folio'),
        ),
    ]
