# Generated by Django 6.0.4 on 2026-04-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Hallazgo')),
                ('area', models.CharField(max_length=150, verbose_name='Área / Departamento')),
                ('criticidad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, verbose_name='Criticidad')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En Revisión (Evidencia)', 'En Revisión (Evidencia)'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=30, verbose_name='Estado')),
                ('fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='auditorias.auditoria', verbose_name='Auditoría Relacionada')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
            ],
            options={
                'verbose_name': 'Hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
